import subprocess
import time
import os
import colorama
from colorama import init, Fore, Back, Style

def vycistit():
    if os.name == "nt":
        os.system("cls")
    else:
        os.system("clear")

def hlavni_cast():
    print(Fore.RED + "#######################################################################")
    print(Fore.GREEN + "#.....................................................................#")
    print(Fore.BLUE + "#.....................................................................#")
    print(Fore.MAGENTA + "#.....................................................................#")
    print(Fore.CYAN + "#.....................................................................#")
    print(Fore.RED + "#....................." + Style.RESET_ALL + "Welcome in Hackers Toolbox" + Fore.RED + "......................#")
    print(Fore.GREEN + "#........................" + Style.RESET_ALL + "Created by: Danb1551" + Fore.GREEN + ".........................#")
    print(Fore.BLUE + "#.........................." + Style.RESET_ALL + "Web: TERMUX.WZ.CZ" + Fore.BLUE + "..........................#")
    print(Fore.MAGENTA + "#......................" + Style.RESET_ALL + "Instagram: hackit.121212" + Fore.MAGENTA + ".......................#")
    print(Fore.CYAN + "#..................." + Style.RESET_ALL + "E-mail: hackit.121212@gmail.com" + Fore.CYAN + "...................#")
    print(Fore.RED + "#...................." + Style.RESET_ALL + "ONLY FOR EDUCATIONAL PURPOSES" + Fore.RED + "....................#")
    print(Fore.GREEN + "#.....................................................................#")
    print(Fore.BLUE + "#.....................................................................#")
    print(Fore.MAGENTA + "#.....................................................................#")
    print(Fore.CYAN + "#.....................................................................#")
    print(Fore.RED + "#######################################################################")
    print("!!!!....The code is not fully completed. Use with caution. I update code in the future....!!!!")

vycistit()
hlavni_cast()
print(Style.RESET_ALL + "Select:")
time.sleep(0.25)
print("")
print("{1.} DDOS Attack")
print("")
print("{2.} Password generator")
print("")
print("{3.} Instagram bruteforce attack")
print("")
volba = int(input("Your select: "))
if volba == 1:
    print("STARTING ATTACK...../")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("STARTING ATTACK.....-")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("STARTING ATTACK.....")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("STARTING ATTACK.....|")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("STARTING ATTACK...../")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("STARTING ATTACK.....-")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("STARTING ATTACK.....|")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("STARTING ATTACK...../")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("STARTING ATTACK.....-")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("STARTING ATTACK.....|")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("STARTING ATTACK...../")
    vycistit()
    hlavni_cast()
    subprocess.call(["python","DDoS-attack1.py"])
if volba == 2:
    print("Password generator is starting............-")
    time.sleep(1)
    vycistit()
    hlavni_cast()
    print("Passwor generator is starting............|")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("Password generator is starting............/")
    time.sleep(1)
    vycistit()
    hlavni_cast()
    print("Passwor generator is starting............-")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("Password generator is starting............|")
    time.sleep(1)
    vycistit()
    hlavni_cast()
    print("Passwor generator is starting............/")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("Password generator is starting............-")
    time.sleep(1)
    vycistit()
    hlavni_cast()
    print("Passwor generator is starting............|")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("Password generator is starting............/")
    time.sleep(1)
    vycistit()
    hlavni_cast()
    print("Passwor generator is starting............-")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("Password generator is starting............|")
    time.sleep(1)
    vycistit()
    hlavni_cast()
    print("Passwor generator is starting............/")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    subprocess.call(["python","passgen.py"])
if volba == 3:
    print("Instagram bruteforce attack is starting............/")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("Instagram bruteforce attack is starting............-")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("Instagram bruteforce attack is starting............|")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("Instagram bruteforce attack is starting............/")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("Instagram bruteforce attack is starting............/")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("Instagram bruteforce attack is starting............-")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("Instagram bruteforce attack is starting............|")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("Instagram bruteforce attack is starting............/")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("Instagram bruteforce attack is starting............/")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("Instagram bruteforce attack is starting............-")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("Instagram bruteforce attack is starting............|")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    print("Instagram bruteforce attack is starting............/")
    time.sleep(0.25)
    vycistit()
    hlavni_cast()
    subprocess.call(["python","instahack.py"])
